### ISSUE TITLE
Inaccurate project lists

### ISSUE THREAD

**Issue by sebbASF** [apache/kibble-website#8]
The 'Who we are' list on the front page
http://kibble.apache.org
does not agree with Whimsy:
https://whimsy.apache.org/roster/committee/kibble

**Comment by sharanf** [comment]
Thanks for highlighting this @sebbASF. I will take a look

**Comment by sharanf** [comment]
Mmm..I thought I had fixed this but it doesn't seem to be working properly. I'll have another go.

**Comment by sebbASF** [comment]
I think you fixed community.html, not index.html...

If the project intends to keep the lists up to date, maybe do this automatically from the Whimsy public data at 
https://whimsy.apache.org/public/committee-info.json
and
https://whimsy.apache.org/public/public_ldap_projects.json (kibble: members)

Note that the latter file contains kibble: owners, which should normally be the same as the committee-info roster, but only the latter is the official list of PMC members.

**Comment by sharanf** [comment]
Hi @sebbASF it's finally fixed now. I found out there were markdown files that needed to be updated and it was those that generated the html ones.
